# action.yml
name: 'SensuFlow'
description: 'Manage Sensu resources using sensuctl prune and create commands'
inputs:
  sensu_api_url:
    description: 'The Sensu API url (alt use env SENSU_API_URL)'
    required: true
  sensu_api_key:
    description: 'The Sensu API key (alt use env SENSU_API_KEY)'
    required: false
  configure_args:
    description: "Optional arguments to pass to sensuctl configure"
    required: false
  sensu_ca_string:
    description: 'Optional Custom CA pem string'
    required: false
  sensu_ca_file:
    description: 'Optional Custom CA pem file location'
    required: false
  namespaces_dir:
    description: "Optional directory to process default: '.sensu/namespaces' "
    required: false
  namespaces_file:
    description: "Optional YAML file containing namespace resource to create default: '.sensu/cluster/namespaces.yml' "
    required: false
  matching_label:
    description: "Optional Sensu label to use in label selector, default: 'sensu.io/workflow'"
    required: false
  matching_condition:
    description: "Optional Sensu label matching condition for label selector, default: \"== 'sensu-flow\""
    required: false
  managed_resources:
    description: 'Optional comma seperated list of managed resources'
    required: false
  resource_authors:
    description: 'Optional comma seperated list users to filter created_by metadata, defaults to sensu-flow'
    required: false
  disable_tls_verify:
    description: 'Optional boolean argument to to disable tls cert verification  default: false'    
    required: false
  disable_sanity_checks:
    description: 'Optional boolean argument to to disable sanity checks  default: false'    
    required: false
  sensu_user:
    description: 'DEPRECATED: The Sensu user to auth (alt use env SENSU_USER)'
    required: false
  sensu_password:
    description: 'DEPRECATED: The Sensu user password (alt use env SENSU_PASSWORD)'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: green
  icon: alert-triangle
