# action.yml
name: 'Sensuflow'
description: 'use sensuctl'
inputs:
  sensu_backend_url:
    description: 'The Sensu backend url (alt use env SENSU_BACKEND_URL'
    required: true
  sensu_user:
    description: 'The Sensu user to auth (alt use env SENSU_USER'
    required: true
  sensu_password:
    description: 'The Sensu user password (alt use env SENSU_PASSWORD'
    required: true
  configure_args:
    description: "optional arguments to pass to sensuctl configure"
    required: false
  sensu_ca:
    description: 'Optional Custom CA pem string'
    required: false
  namespaces_dir:
    description: "Optional directory to process default: 'namespaces' "
    required: false
  workflow_label_selector:
    description: "Option Sensu label selector, default: 'sensu.io/workflow == sensu_flow'"
    required: false
  managed_resources:
    description: 'Optional comma seperated list of managed resources'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: green
  icon: alert-triangle
